baseurl = "https://sergiomoya.me/"
languageCode = "en-EN"
title = "smoya!"
theme = "hugo-future-imperfect"
paginate = 10
disqusShortname = "sergiomoya-me"
googleAnalytics = "UA-84877589-1"
defaultLayout = "post"
defaultContentLanguage = "en"
enableRobotsTXT = true

[permalinks]
    post = "/:year/:month/:filename/"

[taxonomies]
    category = "categories"
    tag = "tags"
    serie = "series"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Once upon a time(), or not."
    # This will appear on the top left of the navigation bar
    navbarTitle          = "sergiomoya.me"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    #viewMorePostLink     = "/blog/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = true
    faviconVersion       = ""

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Sergio Moya"
    paragraph = "Once upon a time(), or not."
    about     = "👶 Papá | 👨‍💻 Platform Engineer at @netlify, formerly @newrelic | 📣 Running @golangbcn | 📢 Co-founder @bcn_eng | 🛩️ Light sport airplane pilot"

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/cropped-my-face-circle.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = true
    width     = "248"
    alt       = "Sergio Moya"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 5

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
   name = "Home"
   url = "/"
   identifier = "fa fa-newspaper-o"
   weight = 1

[[menu.main]]
   name = "Categories"
   url = "/categories/"
   weight = 2

[[menu.main]]
   name = "About"
   url = "/about"
   weight = 3

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "smoya"
    linkedin        = "smoya"
    twitter         = "smoyac"
